import React, { useEffect, useMemo, useState } from "react";
import BrandMark from "@/components/BrandMark";
import EditorialLabel from "@/components/EditorialLabel";
import {
  ArrowUpRight,
  Download,
  ExternalLink,
  FileText,
  Github,
  LoaderCircle,
  Sparkles,
  Tags,
} from "lucide-react";
import { Link } from "wouter";
import {
  getPublicWorkspace,
  type PublicWorkspace,
  type WorkspaceChangeType,
} from "@/lib/publicApi";

const typeLabels: Record<WorkspaceChangeType, string> = {
  regulation: "Regulation",
  enforcement: "Legislation and enforcement",
  market_access: "Market access",
  guidance: "Guidance and standards",
  other: "Other policy movement",
};

const typeOrder: WorkspaceChangeType[] = [
  "regulation",
  "enforcement",
  "market_access",
  "guidance",
  "other",
];

function formatDate(value: string | null | undefined) {
  if (!value) return "Not yet run";
  return new Date(value).toLocaleDateString(undefined, {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}

function downloadText(filename: string, content: string) {
  if (typeof window === "undefined") return;
  const url = window.URL.createObjectURL(
    new Blob([content], { type: "text/markdown;charset=utf-8" })
  );
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  window.URL.revokeObjectURL(url);
}

function ideaDownload(
  idea: PublicWorkspace["ideas"][number],
  change: PublicWorkspace["changes"][number],
  expansion: PublicWorkspace["expansions"][number] | undefined
) {
  const body = [
    `# ${idea.title}`,
    "",
    `Generated from the ${typeLabels[change.change_type].toLowerCase()} change published by ${change.source_name}.`,
    "",
    "## Policy change",
    "",
    `**${change.headline}**`,
    "",
    change.summary,
    "",
    `- Jurisdiction: ${change.jurisdiction?.name ?? "Global"}`,
    `- Importance: ${change.importance}`,
    `- Official source: ${change.canonical_url}`,
    "",
    "## Potential project or idea",
    "",
    idea.summary,
    "",
    "## Why it follows",
    "",
    idea.rationale,
    "",
    expansion?.body_markdown ??
      "The combined rough expansion is not available for this idea yet.",
    "",
    "---",
    `Generated by Brief on ${new Date().toISOString()}.`,
  ].join("\n");
  downloadText("brief-selected-idea.md", body);
}

export default function Workspace() {
  const [workspace, setWorkspace] = useState<PublicWorkspace | null>(null);
  const [status, setStatus] = useState<"loading" | "ready" | "error">(
    "loading"
  );
  const [selectedType, setSelectedType] = useState<WorkspaceChangeType | "all">(
    "all"
  );
  const [selectedIdeaId, setSelectedIdeaId] = useState<string | null>(null);

  useEffect(() => {
    const controller = new AbortController();
    void getPublicWorkspace(controller.signal)
      .then(nextWorkspace => {
        setWorkspace(nextWorkspace);
        setStatus("ready");
      })
      .catch(error => {
        if (error instanceof DOMException && error.name === "AbortError")
          return;
        setStatus("error");
      });
    return () => controller.abort();
  }, []);

  const visibleChanges = useMemo(
    () =>
      workspace?.changes.filter(
        change => selectedType === "all" || change.change_type === selectedType
      ) ?? [],
    [selectedType, workspace]
  );

  const ideasByChange = useMemo(() => {
    const map = new Map<string, PublicWorkspace["ideas"]>();
    for (const idea of workspace?.ideas ?? []) {
      const current = map.get(idea.change_id) ?? [];
      current.push(idea);
      map.set(idea.change_id, current);
    }
    return map;
  }, [workspace]);

  const expansionByIdea = useMemo(
    () =>
      new Map((workspace?.expansions ?? []).map(item => [item.idea_id, item])),
    [workspace]
  );

  const selectedIdea = workspace?.ideas.find(
    idea => idea.id === selectedIdeaId
  );
  const selectedChange = selectedIdea
    ? workspace?.changes.find(change => change.id === selectedIdea.change_id)
    : undefined;
  const selectedExpansion = selectedIdea
    ? expansionByIdea.get(selectedIdea.id)
    : undefined;

  const retry = () => {
    window.location.reload();
  };

  return (
    <main className="min-h-screen bg-[#07080b] text-white">
      <header className="mx-auto flex w-full items-center justify-between gap-4 px-6 py-5 sm:px-10 lg:px-16 xl:px-20">
        <Link href="/" aria-label="Brief home">
          <BrandMark compact tone="light" />
        </Link>
        <nav className="flex items-center gap-2 text-xs font-semibold text-white/55 sm:gap-5">
          <Link className="transition hover:text-white" href="/discover">
            Discover
          </Link>
          <a
            className="transition hover:text-white"
            href="https://github.com/koustavdatascience/brief-global-open"
            rel="noreferrer"
            target="_blank"
          >
            GitHub
          </a>
          <Link
            className="rounded-full border border-white/15 px-3 py-2 text-white transition hover:border-white/35 hover:bg-white/5"
            href="/"
          >
            About Brief
          </Link>
        </nav>
      </header>

      <section className="mx-auto w-full px-6 pb-16 pt-16 sm:px-10 lg:px-16 lg:pt-24 xl:px-20">
        <div className="grid gap-10 border-b border-white/10 pb-14 lg:grid-cols-[minmax(0,1fr)_19rem] lg:items-end lg:gap-16">
          <div>
            <EditorialLabel>Brief workspace</EditorialLabel>
            <h1 className="mt-5 max-w-5xl text-5xl font-medium leading-[0.94] tracking-[-0.06em] sm:text-6xl lg:text-[5rem]">
              Policy changes, organized into what you can do next.
            </h1>
            <p className="mt-6 max-w-2xl text-base leading-7 text-white/55">
              Every Sunday and Wednesday, Brief refreshes this public workspace
              with source-linked changes, grouped by type, and grounded project
              ideas for people watching policy, software, and markets together.
            </p>
          </div>
          <aside className="rounded-2xl border border-white/10 bg-white/[0.035] p-5">
            <div className="flex items-center justify-between gap-3">
              <span className="font-mono text-[0.58rem] uppercase tracking-[0.15em] text-white/40">
                Next cycle
              </span>
              <Tags className="h-4 w-4 text-[#aeb9ff]" />
            </div>
            <p className="mt-6 text-xl font-medium tracking-[-0.04em] text-white">
              Sundays + Wednesdays
            </p>
            <p className="mt-1 text-sm text-white/50">
              09:00 IST · Asia/Kolkata
            </p>
            <div className="mt-6 border-t border-white/10 pt-4 text-xs leading-5 text-white/45">
              {workspace?.schedule.next_window ??
                "The next cycle will refresh this public workspace."}
            </div>
          </aside>
        </div>
      </section>

      <section className="mx-auto w-full px-6 pb-24 sm:px-10 lg:px-16 xl:px-20">
        <div className="flex flex-wrap items-end justify-between gap-5 border-b border-white/10 pb-5">
          <div>
            <EditorialLabel>Latest cycle</EditorialLabel>
            <p className="mt-2 text-sm text-white/50">
              {workspace?.cycle
                ? `${formatDate(workspace.cycle.completed_at ?? workspace.cycle.scheduled_for)} · ${workspace.cycle.change_count} changes · ${workspace.cycle.idea_count} ideas`
                : "No completed cycle has been published yet."}
            </p>
          </div>
          <div className="flex flex-wrap gap-2">
            <button
              className={`rounded-full border px-3 py-2 text-xs font-semibold transition ${selectedType === "all" ? "border-white bg-white text-[#07080b]" : "border-white/15 text-white/55 hover:border-white/35 hover:text-white"}`}
              onClick={() => setSelectedType("all")}
              type="button"
            >
              All changes
            </button>
            {typeOrder.map(type => (
              <button
                className={`rounded-full border px-3 py-2 text-xs font-semibold transition ${selectedType === type ? "border-[#aeb9ff] bg-[#aeb9ff] text-[#07080b]" : "border-white/15 text-white/55 hover:border-white/35 hover:text-white"}`}
                key={type}
                onClick={() => setSelectedType(type)}
                type="button"
              >
                {typeLabels[type]}
              </button>
            ))}
          </div>
        </div>

        {status === "loading" ? (
          <div className="flex items-center gap-3 py-16 text-sm text-white/50">
            <LoaderCircle className="h-4 w-4 animate-spin" />
            Loading the latest public cycle…
          </div>
        ) : null}
        {status === "error" ? (
          <div className="mt-8 rounded-2xl border border-[#a94c37]/40 bg-[#a94c37]/10 p-6 text-sm text-white/70">
            <p>The public workspace could not be loaded.</p>
            <button
              className="mt-3 font-semibold text-white underline underline-offset-4"
              onClick={retry}
              type="button"
            >
              Retry
            </button>
          </div>
        ) : null}
        {status === "ready" && visibleChanges.length === 0 ? (
          <div className="border-b border-white/10 py-20">
            <Sparkles className="h-5 w-5 text-[#aeb9ff]" />
            <h2 className="mt-5 text-2xl font-medium tracking-[-0.04em]">
              The next source-linked cycle is on its way.
            </h2>
            <p className="mt-3 max-w-xl text-sm leading-6 text-white/50">
              When the first Sunday or Wednesday cycle completes, changes will
              appear here grouped by policy type, with grounded ideas available
              to select and expand.
            </p>
          </div>
        ) : null}

        <div className="divide-y divide-white/10">
          {visibleChanges.map(change => {
            const ideas = ideasByChange.get(change.id) ?? [];
            return (
              <article className="py-10 lg:py-12" key={change.id}>
                <div className="grid gap-8 lg:grid-cols-[12rem_minmax(0,1fr)_18rem] lg:gap-12">
                  <div className="text-xs uppercase tracking-[0.12em] text-white/40">
                    <span>{change.jurisdiction?.flag_emoji ?? "◎"}</span>{" "}
                    {change.jurisdiction?.name ?? "Global"}
                    <br />
                    <span className="mt-2 inline-block normal-case tracking-normal text-white/35">
                      {formatDate(change.published_at)}
                    </span>
                  </div>
                  <div>
                    <div className="flex flex-wrap items-center gap-2 text-xs uppercase tracking-[0.11em] text-white/45">
                      <span className="rounded-full border border-[#aeb9ff]/30 bg-[#aeb9ff]/10 px-2 py-1 text-[#cbd2ff]">
                        {typeLabels[change.change_type]}
                      </span>
                      <span>{change.importance}</span>
                    </div>
                    <h2 className="mt-4 max-w-3xl text-2xl font-medium leading-tight tracking-[-0.04em] sm:text-3xl">
                      {change.headline}
                    </h2>
                    <p className="mt-3 max-w-3xl text-sm leading-7 text-white/55">
                      {change.summary}
                    </p>
                    <a
                      className="mt-4 inline-flex items-center gap-2 text-xs font-semibold text-white/65 transition hover:text-white"
                      href={change.canonical_url}
                      rel="noreferrer"
                      target="_blank"
                    >
                      Read {change.source_name}
                      <ArrowUpRight className="h-3.5 w-3.5" />
                    </a>
                  </div>
                  <div className="rounded-2xl border border-white/10 bg-white/[0.035] p-5">
                    <div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.12em] text-[#cbd2ff]">
                      <Sparkles className="h-3.5 w-3.5" />
                      Potential idea
                    </div>
                    {ideas.length ? (
                      <div className="mt-5 space-y-3">
                        {ideas.map(idea => (
                          <button
                            aria-label={`${selectedIdeaId === idea.id ? "Collapse" : "Expand"} brief PRD for ${idea.title}`}
                            className={`w-full rounded-xl border p-4 text-left transition ${selectedIdeaId === idea.id ? "border-[#aeb9ff]/70 bg-[#aeb9ff]/10" : "border-white/10 bg-black/10 hover:border-white/25"}`}
                            key={idea.id}
                            onClick={() =>
                              setSelectedIdeaId(current =>
                                current === idea.id ? null : idea.id
                              )
                            }
                            type="button"
                          >
                            <span className="block text-sm font-semibold leading-5 text-white">
                              {idea.title}
                            </span>
                            <span className="mt-3 block text-[0.62rem] uppercase tracking-[0.12em] text-white/35">
                              {selectedIdeaId === idea.id
                                ? "Selected"
                                : "Select to expand"}
                            </span>
                          </button>
                        ))}
                      </div>
                    ) : (
                      <p className="mt-5 text-sm leading-6 text-white/45">
                        No grounded project idea was generated for this change.
                      </p>
                    )}
                  </div>
                </div>
              </article>
            );
          })}
        </div>
      </section>

      {selectedIdea && selectedChange ? (
        <section className="border-y border-[#aeb9ff]/20 bg-[#aeb9ff]/[0.06]">
          <div className="mx-auto w-full px-6 py-12 sm:px-10 lg:px-16 lg:py-16 xl:px-20">
            <div className="flex flex-wrap items-start justify-between gap-6">
              <div>
                <EditorialLabel>Brief PRD</EditorialLabel>
                <h2 className="mt-4 max-w-4xl text-3xl font-medium tracking-[-0.05em] sm:text-4xl">
                  {selectedIdea.title}
                </h2>
                <p className="mt-3 max-w-2xl text-sm leading-7 text-white/55">
                  A concise, source-grounded product brief covering delivery,
                  users, workflow, and economic logic in one combined idea.
                </p>
              </div>
              <button
                className="inline-flex items-center gap-2 rounded-full bg-white px-4 py-3 text-xs font-bold text-[#07080b] transition hover:bg-[#dfe3ff]"
                onClick={() =>
                  ideaDownload(selectedIdea, selectedChange, selectedExpansion)
                }
                type="button"
              >
                <Download className="h-3.5 w-3.5" />
                Download brief PRD
              </button>
            </div>
            <div className="mt-10 grid gap-8 lg:grid-cols-[minmax(0,1fr)_18rem] lg:gap-14">
              <div className="whitespace-pre-wrap text-sm leading-7 text-white/70">
                {selectedExpansion?.body_markdown ??
                  "The combined expansion is not available for this idea yet. The source-linked idea above remains available for download and review."}
              </div>
              <aside className="self-start rounded-2xl border border-white/10 bg-black/15 p-5 text-sm leading-6 text-white/50">
                <FileText className="h-4 w-4 text-[#aeb9ff]" />
                <p className="mt-4 font-semibold text-white/80">
                  Grounded in the source
                </p>
                <p className="mt-1">{selectedChange.source_name}</p>
                <a
                  className="mt-4 inline-flex items-center gap-2 text-xs font-semibold text-white/70 hover:text-white"
                  href={selectedChange.canonical_url}
                  rel="noreferrer"
                  target="_blank"
                >
                  Open official source
                  <ExternalLink className="h-3.5 w-3.5" />
                </a>
              </aside>
            </div>
          </div>
        </section>
      ) : null}

      <footer className="mx-auto flex w-full max-w-[1600px] flex-col gap-3 px-6 py-10 text-sm text-white/40 sm:flex-row sm:items-center sm:justify-between sm:px-10 lg:px-16 xl:px-20">
        <span>Brief — public policy intelligence workspace</span>
        <a
          className="inline-flex items-center gap-2 font-semibold text-white/55 hover:text-white"
          href="https://github.com/koustavdatascience/brief-global-open"
          rel="noreferrer"
          target="_blank"
        >
          <Github className="h-3.5 w-3.5" />
          Open source on GitHub
        </a>
      </footer>
    </main>
  );
}
